name: Install dependencies and run tests

on:
  pull_request:
    types: [opened, synchronize]
  # Run the cleanup job once a week
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          # Install pnpm globally
          cache: 'npm'
          run: 'npm install -g pnpm'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
          # Delete cache entries older than 7 days
          delete-older-than: 7d