name: Install dependencies and run tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          # Install pnpm globally
          cache: 'npm'
          run: 'npm install -g pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test